behaviors:
  Stacker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      beta: 5.0e-3
      buffer_size: 100
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      hidden_units: 128
      memory_size: 128
      normalize: false
      num_epoch: 3
      num_layers: 2
      use_recurrent: false
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5.0e4
    time_horizon: 64
    summary_freq: 10000
